### ISSUE TITLE
App API complains about 'Docker Socket' with 'Docker Socket Proxy' set up.

### ISSUE THREAD

**Issue by ShapeShifter499** [cloud-py-api/app_api#100]
### Describe the bug

I have set up Nextcloud AIO and App API complains about the 'docker socket' although 'Docker Socket Proxy' is set up. It seems like it's a irreverent error since it displays that it has connected successfully to the proxy. See the following screenshot included.

### Steps/Code to Reproduce

Install Nextcloud AIO, select for 'Docker Socket Proxy' as one of the optional containers to install. Run into this error displayed in the Nextcloud Web Interface. 

### Expected Results

No error is shown.

### Actual Results

![Screenshot from 2023-10-22 04-44-39](https://github.com/cloud-py-api/app_api/assets/388665/577ec4c0-9322-4aa1-a7b8-c39a5bcf868d)

### Setup configuration

Running Nextcloud AIO v7.5.0 BETA generated after this https://github.com/nextcloud/all-in-one/issues/3566

App API = 1.0.1
Nextcloud = 27.1.2

**System Specs**
Operating System: Linux 6.1.55-1-MANJARO x86_64
CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 cores)
Memory: 15.50 GB

EDIT: There's 16GB of RAM installed, but above is just what I got from the system info page of Nextcloud.

**Comment by andrey18106** [comment]
Thank you for reporting. It's a known problem, will be fixed in the next release.
