### ISSUE TITLE
Failed when setting up dev environment

### ISSUE THREAD

**Issue by kevinkuan1969** [cloud-py-api/app_api#156]
### Describe the bug

New to App_API and try to explore but failed during the dev environment setup.
Hope some help and thanks in advance.

![image](https://github.com/cloud-py-api/app_api/assets/80019930/0e7efa3c-4d0d-4aa9-8154-fc6a1015fd99)

### Steps/Code to Reproduce

Get last version from GitHub[](https://cloud-py-api.github.io/app_api/DevSetup.html#get-last-version-from-github)

git clone https://github.com/cloud-py-api/app_api.git

Move to the app_api directory with shell:

cd app_api

Then, build NPM and JS with shell:

npm ci && npm run build

### Expected Results

No errors as below:

ERROR in [eslint] EACCES: permission denied, mkdir '/var/www/nextcloud/apps/app_api/node_modules/.cache/eslint-webpack-plugin'

ERROR in [stylelint] EACCES: permission denied, mkdir '/var/www/nextcloud/apps/app_api/node_modules/.cache/stylelint-webpack-plugin'

### Actual Results

Can revoke following external applications:

[talk_bot_ai_example](https://github.com/cloud-py-api/talk_bot_ai_example)
[upscaler_example](https://github.com/cloud-py-api/upscaler_example)

### Setup configuration

Nextcloud 28.0.0
App_API   1.4.2 
Ubuntu 23.10

**Comment by bigcat88** [comment]
It is permissions problems.

1. do you execute "npm ci && npm run build" from root user?
2. can I see output of `ls -la` in the root of cloned AppAPI?
3. Sometimes, cleaning the npm cache can resolve permission issues: npm cache clean --force

**Comment by bigcat88** [comment]
closed as no comments received during 3 weeks.
feel free to raise new issue or write in this and we will reopen it.
