### ISSUE TITLE
Lack of clarity in dockumentation

### ISSUE THREAD

**Issue by StefanRichterHuber** [cloud-py-api/app_api#160]
### Describe the bug

I am trying  to build an java ExApp using your API and need a little more type safety :smile: than the provided python apps. This way I stumbled over several inconsistencies in the documentation.

## Installation FLow

<https://cloud-py-api.github.io/app_api/tech_details/InstallationFlow.html>

### Enabled

Then enabled request does not seem to have a payload but a query parameter `enabled` which is an integer value (1 enabled, 0 disabled).

e.g. the request is an PUT on `http://expapp:2432/enabled?enabled=1`

### Logging

<https://cloud-py-api.github.io/app_api/tech_details/api/logging.html>

Please indicate that log level is an int ( if correct, please link [Nextcloud doc](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level) )

```json
{
        "level": "loglevel",
        "message": "message",
}
```

### AppConfig

<https://cloud-py-api.github.io/app_api/tech_details/api/appconfig.html>

Request data seems to be of the wrong format.
Had more success with (like in [preferences](https://cloud-py-api.github.io/app_api/tech_details/api/preferences.html)):

```json
{
        "configKey": "key",
        "configValue": "value"
}
```

Still unsure of the value `sensitive`? JSON boolean, int 1/0 or String with true/false?

For both the the block `Get app config values` the documented response data seems to be insufficient.

Actual response is more like

```json
{"ocs":
    {"meta": {"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},
    "data":[
        { "configkey": "key1", "configvalue": "value1" },
        { "configkey": "key2", "configvalue": "value2" },
        { "configkey": "key3", "configvalue": "value3" },
]}}

```

Same might be true for the [preferences](https://cloud-py-api.github.io/app_api/tech_details/api/preferences.html) but not yet tested.

Also please indicate if there is any UI (planned) to configure AppConfig or Preferences.

### Get list of NC users

<https://cloud-py-api.github.io/app_api/tech_details/api/utils.html>
The  the documented response data seems to be insufficient.

Actual response is more like

```json
{"ocs":
    {"meta": {"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},
    "data":["user1", "user2", "user3"]}
}


### Steps/Code to Reproduce

Read documentation and try to build an app

### Expected Results

Documentation matches the actual api

### Actual Results

See text

### Setup configuration

exapp_api = 1.4.3 nextcloud=27.1.5

**Comment by bigcat88** [comment]
Done(I hope).

_I didn’t indicate what the UI for settings will be done in the future, because we don’t know, we’ll find out how and what it will be this week, I plan to do it tomorrow._

Thank you very much for this issue, it's nice to see such well written issue.

**Comment by bigcat88** [comment]
Declarative settings docs is here: https://cloud-py-api.github.io/app_api/tech_details/api/settings.html
Still needed PR was not merged into server, but I hope it will till NC 29 get released.
