### ISSUE TITLE
I18N for Notifications (and other futher message directly to one user)

### ISSUE THREAD

**Issue by StefanRichterHuber** [cloud-py-api/app_api#163]
### Describe why it is important and where it will be useful

 Nextcloud each user can set the applications language to have the best user experience and lowest entry barrier. 
Currently the available APIs give no indication on  the preferred language for the user.

### Describe your proposed solution

Possible solutions:

1) Send an additional `X-USER-LANG` header with each request for an user to given the app the possibility to react in the users language.
Pro: Downwards compatible. Con: App has to keep track of the user language internally
2) Extend the [Get list of NC users](https://cloud-py-api.github.io/app_api/tech_details/api/utils.html) endpoint with additional metadata per user, especially language but also user group for additional authorization.
Pro: Best extensible place to put additional user metadata. Con: Not downwards compatible.
3) Enhance the [Notification API](https://cloud-py-api.github.io/app_api/tech_details/api/notifications.html) to accept `rich_subject` and `rich_message` in multiple languages and let the ui choose which one. Pro: Works without any additional information about the user. Con: Not downwards compatible, depending on the implementation.

```json
{
        "params": {
                "object": "app_api",
                "object_id": "app_api_id",
                "subject_type": "app_api_ex_app",
                "subject_params": {
                        "rich_subject":  [
                               {
                                       "lang": "en",
                                      "text": ""Image {file} successfully upscaled!"
                              }, 
                               {
                                       "lang": "de",
                                      "text": ""Bild {file} erfolgreich vergrößert!"
                              }, 
                         ],
                        "rich_subject_params": {
                                "file": {
                                        "type": "file",
                                        "id": 123,
                                        "name": "upscaled_image_name",
                                        "path": "path/to/upscaled_image_name"
                                }
                        },
                        "rich_message"://  ... see rich subject
                        "rich_message_params": {
                                "user": {
                                        "type": "user",
                                        "id": "admin",
                                        "name": "admin"
                                }
                        },
                        "link": "http(s)://nextcloud.local/index.php/apps/files/?fileid=123"
                }
        }
}

```

**Comment by bigcat88** [comment]
Implemented in AppAPI `2.2.0`
