### ISSUE TITLE
Configure ExApp containers with "RestartPolicy: always"

### ISSUE THREAD

**Issue by andrey18106** [cloud-py-api/app_api#175]
### Describe why it is important and where it will be useful

This is required to be a default option in case of server restart to keep ExApps containers running.

### Describe your proposed solution

Adjust ExApp containers creation with `HostConfig.RestartPolicy: always`. This will mitigate containers in disabled state after host server (or daemon server) restart.

**Comment by bigcat88** [comment]
note: this should be a docker daemon option, to be configurable and disabled if needed, imho.
