### ISSUE TITLE
Image not returned to chat or folder with 2FA enabled

### ISSUE THREAD

**Issue by MrNunu** [cloud-py-api/app_api#181]
Installed this on AIO 7.9.0 (Nextcloud 27.1.5) and while the logs seem to show the app responds to @image prompt, I'm not getting an image back either in chat or in the folder. 

> TRACE:    172.18.0.8:35626 - HTTP connection made
> TRACE:    172.18.0.8:35626 - ASGI [12] Started scope={'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('172.18.0.11', 15888), 'client': ('172.18.0.8', 35626), 'scheme': 'http', 'root_path': '', 'headers': '<...>', 'state': {}, 'method': 'POST', 'path': '/stable_diffusion', 'raw_path': b'/stable_diffusion', 'query_string': b''}
> TRACE:    172.18.0.8:35626 - ASGI [12] Receive {'type': 'http.request', 'body': '<322 bytes>', 'more_body': False}
> TRACE:    172.18.0.8:35626 - ASGI [12] Send {'type': 'http.response.start', 'status': 200, 'headers': '<...>'}
> image generated: 22.71879433398135s
> [401] Unauthorized <request: GET /ocs/v1.php/cloud/capabilities>
> offloading model
> INFO:     172.18.0.8:35626 - "POST /stable_diffusion HTTP/1.1" 200 OK
> TRACE:    172.18.0.8:35626 - ASGI [12] Send {'type': 'http.response.body', 'body': '<0 bytes>'}
> TRACE:    172.18.0.8:35626 - ASGI [12] Completed
> task added
> loading model
> Loading pipeline components...:  14%|█▍        | 1/7 [00:00<00:04,  1.41it/s]TRACE:    172.18.0.8:35626 - HTTP connection lost
> Loading pipeline components...: 100%|██████████| 7/7 [00:02<00:00,  2.84it/s]
> model loaded: 2.475664479075931s
> generating image
> 100%|██████████| 1/1 [00:08<00:00,  8.17s/it]

I do see the 401 error in there but unsure how to deal with it. 

Here are some screenshots showing what I think is a successful installation. 

![image](https://github.com/cloud-py-api/ai_image_generator_bot/assets/130261554/0a5d2073-936f-4b2f-9d36-9cadcd667fd5)

![image](https://github.com/cloud-py-api/ai_image_generator_bot/assets/130261554/9976f73e-f11e-487e-854a-e4e2b36dd16d)

![image](https://github.com/cloud-py-api/ai_image_generator_bot/assets/130261554/c6b3eeb7-0849-437b-835e-b7ad1df3be1f)

**Comment by andrey18106** [comment]
@MrNunu Thank you again for informing. Fix in server will be included starting from Nextcloud 27.1.6 (https://github.com/nextcloud/server/pull/42520)
