### ISSUE TITLE
Style and script urls are not generated correctly because of the appended cache buster

### ISSUE THREAD

**Issue by splitt3r** [cloud-py-api/app_api#193]
Thanks for this great app. I'm really looking forward to what people will create with this.

I played around a bit and have some problems. I created a .NET microservice which should be able to create its own top menu entry with a for now very simple page.

The source code is here https://github.com/splitt3r/nextcloud-dotnet-microservice

My problem now is that i can't get the style and script loading to work:

![image](https://github.com/cloud-py-api/app_api/assets/1869584/9a9b6699-541b-4824-a971-9ac7f1ce28d4)

![image](https://github.com/cloud-py-api/app_api/assets/1869584/f8cef306-8b8f-4360-9b3b-8a0d5d768541)

It tries to load: http://localhost:8080/custom_apps/app_api/css/proxy/dotnet_microservice/style.css
It should in theory also load : http://localhost:8080/custom_apps/app_api/js/proxy/dotnet_microservice/script.js (which it does not yet)

What works is: http://localhost:8080/apps/app_api/proxy/dotnet_microservice/style.css
And also: http://localhost:8080/apps/app_api/proxy/dotnet_microservice/script.js
Content type etc. looks good for those two urls.

Maybe you have a hint what i'm doing wrong here. Thanks in advance

**Comment by bigcat88** [comment]
<img width="904" alt="image" src="https://github.com/cloud-py-api/app_api/assets/13381981/10a699c1-015e-4817-a59f-29697573d25f">

`http://stable27.local/index.php/apps/app_api/proxy/ui_example/js/ui_example-main.js`


> It tries to load: http://localhost:8080/custom_apps/app_api/css/proxy/dotnet_microservice/style.css It should in theory also load : http://localhost:8080/custom_apps/app_api/js/proxy/dotnet_microservice/script.js (which it does not yet)

I do not know why there is a `css` or `js` in URL before `proxy`.

**Comment by bigcat88** [comment]
https://github.com/cloud-py-api/app_api/blob/f6e7408d85f3066c6e77aaec3094baa9fcdc2d53/lib/Middleware/ExAppUiMiddleware.php#L24-L40


Hmm, looks like we have a bug in code, that should replace `js` and `css`...

**Comment by bigcat88** [comment]
@splitt3r can you send us a page source or `href=....` from page source with these lines?

**Comment by bigcat88** [comment]
Also please post the records from `oc_ex_ui_scripts` table.

**Comment by bigcat88** [comment]
Could you apply the changes from the linked PR and say whether there are enough changes in it or not?

**Comment by bigcat88** [comment]
*I am not sure will it work when apps installed in "custom_apps" dir and "custom_app" will be in url, but probably if needed we can handle that in regex expression too.
But as fat as I know, applications are always mapped in Url to 'apps' folder, no matter how folder is called on the filesystem.*

You tell me what works for your setup and what is no, I will correct PR and when all will be working we can merge this PR.

**Comment by bigcat88** [comment]
fixed in published `1.4.6` version
