### ISSUE TITLE
I18N - Clarification for string

### ISSUE THREAD

**Issue by roliverio** [cloud-py-api/app_api#200]
### Describe why it is important and where it will be useful

Improving I18n/l10n work

### Describe your proposed solution

in _src/components/DaemonConfig/RegisterDaemonConfigModal.vue:_

"accepts-deploy-id:" doesn't have more context, if we're referring to the docker daemon that's currently the one that supports it, a good rephrase could be: "Current daemon supports accept-deploy-id?" or maybe methods. (i'm not entirely sure if this is merely a status prompt or not) however, as we cannot directly translate: "accepts-deploy-id" it should be treated like a whole string.

Thanks for any clarification / minor correction of the string to appropriately update translations.

**Comment by bigcat88** [comment]
My proposal:

1. Remove "Supported daemon accepts-deploy-id" warning completly.

2. "Select daemon accepts-deploy-id" -> "App Installation Method"

**Comment by bigcat88** [comment]
That UI part was rewritten 👍
