### ISSUE TITLE
AppAPI 2.0 Release Information

### ISSUE THREAD

**Issue by bigcat88** [cloud-py-api/app_api#213]
**We are preparing with joy and optimism for the release of AppAPI version 2.0**

Ref: #212

The main innovations of this version for Administrators:
1. Implemented Docker Socket Proxy (https://github.com/cloud-py-api/docker-socket-proxy)
2. Added the ability to install applications **on a remote docker** using Docker Socket Proxy **with HTTPS**
3. The Daemon creation UI has been rewritten, **creating demons using selectable templates** has been implemented
4. Creation of Daemons now is much simpler with less params, **Unraid**/**Proxmox**/etc.. are now easy supported.

The main cool difference for the developers:
1. Nextcloud Talk Bots now should use AppAPI authentication for incoming endpoints
2. Field `protocol` in `info.xml` is deprecated and ignored from now. All ExApps should implement only simple HTTP.
3. `occ app_api:app:register appName manual_install --json-info` - does not require `protocol` or `host` fields anymore, these values are from now calculated based on Daemon values.
4. If you have part of application in PHP, then to communicate with ExApp you should use `exAppRequest` or `exAppRequestWithUserInit` from PublicFunctions.php, as it handles new Auth correctly for Docker Socket Proxy installs.

**How to Update from 1.x version to 2.0 version?**

Ideal variant is:

1. Remove all ExApps
2. Remove all Daemons
3. Uninstall AppAPI 1.4.x
4. Install AppAPI 2.0

Variant when you first got update to AppAPI 2.0 and after that found this topic:

0. Try Remove all ExApps and after that all Daemons, after that uninstall AppAPI.
1. Truncate `oc_ex_apps`, `oc_ex_apps_daemons`, `oc_appconfig_ex`, `oc_preferences_ex ` tables.
2. For talk bots, truncate: `oc_talk_bots_conversation`, `oc_talk_bots_server` tables.
3. Reset memcache(in case of redis, do: `redis-cli` and `flushAll` after that inside redis command line)

**_Feel free to ask questions inside this topic if something is unclear._**

**Comment by szaimen** [comment]
> * Remove all ExApps
> * Remove all Daemons
> * Uninstall AppAPI 1.4.x
> * Install AppAPI 2.0

This is not possible in AIO. Cannot you take care of this during the upgrade of the app?

**Comment by szaimen** [comment]
What happens if you dont do this and simply update the app?

**Comment by bigcat88** [comment]
_IMHO: in AIO, in theory, everything should be fine with the deployment daemon, since AIO Docker Socket Proxy did not changed._

Related to ExApps: there were no so much of them, and the changes were only to TalkBots API.

**Comment by szaimen** [comment]
All right, thanks! I guess we dont need to adjust things in AIO then.
