### ISSUE TITLE
Error with apps supporting /init

### ISSUE THREAD

**Issue by red3333** [cloud-py-api/app_api#255]
### Describe the bug

While trying to install and use `ai_image_generator_bot`, I fell on an error with the `/init` requests:
- the app supports `/init` request, this starts the download of libraries and periodically send progress status indications (`/ocs/v1.php/apps/app_api/apps/status/ai_image_generator_bot?format=json` with content containing progress percentage).
- when a progress status indication reaches the app_api authorization check, the app is not yet enabled, so the `if (!$exApp->getEnabled())` (Service/AppAPIService.php [198]) returns an authentication error
- the app download process crashes on the error, and the download stops (and never finishes), so the app is never operational.

If I comment the test on `getEnabled()` part, the app installs and runs correctly (including downloading libraries).
To be noted that if the libraries are already downloaded (cached), the `/init` process crashes, but a later `/activate` will work, as the app is already operational with all its libraries...

### Steps/Code to Reproduce

install eg. ai_image_generator_bot after cleaning it persistent storage if present.

### Expected Results

App installs, initializes and activates successfully.

### Actual Results

The App is installs, but never initializes. The app is not working.

### Setup configuration

Nextcloud 28.0.3
app_api 2.3.1

**Comment by bigcat88** [comment]
I can't reproduce this. 

ExApp first get enable state and after that "/init" step got started.

https://github.com/cloud-py-api/app_api/blob/f7eefb801b8350039b1f693dd0259377e080bf28/lib/Service/AppAPIService.php#L383-L408


Was there any logs messages related to this? `ExApp %s initialization timed out (%sm)`

**Comment by bigcat88** [comment]
What you described - that behaviour was in previous AppAPI versions, but after that I simplified it to first enable ExApp and after that call "/init".

Still there can be errors somewhere, but if we find any, I'm willing to fix them.
