### ISSUE TITLE
Index name "nid" for table "oc_social_3_stream" collides with the constraint on table "oc_social_3_cache_actor"

### ISSUE THREAD

**Issue by RainerEmrich** [cloud-py-api/app_api#266]
### Describe the bug

Trying to install and activate AppApi gives the following Error.
{"reqId":"Fl4gPd9I1hzOnXDHfpUa","level":3,"time":"2024-04-08T10:26:02+00:00","remoteAddr":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","user":"xxxxxxxxxxxxx","app":"settings","method":"POST","url":"/settings/apps/enable","message":"could not enable apps","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0","version":"28.0.4.1","exception":{"Exception":"InvalidArgumentException","Message":"Index name \"nid\" for table \"oc_social_3_stream\" collides with the constraint on table \"oc_social_3_cache_actor\".","Code":0,"Trace":[{"file":"/var/www/nc_01/nextcloud/lib/private/DB/MigrationService.php","line":443,"function":"ensureUniqueNamesConstraints","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/var/www/nc_01/nextcloud/lib/private/DB/MigrationService.php","line":401,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/var/www/nc_01/nextcloud/lib/private/Installer.php","line":155,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"/var/www/nc_01/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":454,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/var/www/nc_01/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/var/www/nc_01/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nc_01/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nc_01/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nc_01/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nc_01/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nc_01/nextcloud/lib/private/DB/MigrationService.php","Line":691,"message":"could not enable apps","exception":{},"CustomMessage":"could not enable apps"}}

### Steps/Code to Reproduce

Trying to install AppApi.

### Expected Results

AppApi is installed and activated.

### Actual Results

AppAPi is installed but not activated.

### Setup configuration

nextcloud 28.0.4.1, AppApi 2.4.0, mariadb 10.6.17

**Comment by andrey18106** [comment]
Hi, @RainerEmrich ! This is not related to AppAPI, but to the Social app (https://github.com/nextcloud/social/issues/1871).
Closing as unrelated.
