### ISSUE TITLE
ExApp init timeout not saved

### ISSUE THREAD

**Issue by tacruc** [cloud-py-api/app_api#287]
### Describe the bug

![image](https://github.com/cloud-py-api/app_api/assets/402891/24d900bf-1f07-449f-bb37-527a2c2305b3)

I set the timeout to 3000 minutes, but the ai_image_generation_app initaliation stops failes after 40min.

![image](https://github.com/cloud-py-api/ai_image_generator_bot/assets/402891/0961b7eb-d4b1-479f-9f64-854434913097)

![image](https://github.com/cloud-py-api/ai_image_generator_bot/assets/402891/c9af78ef-6cd1-49b9-a44e-95ecf56071f6)

`[app_api] Fehler: ExApp ai_image_generator_bot initialization failed. Error: ExApp ai_image_generator_bot initialization timed out (2400m)  -- um 08.05.2024, 09:35:01`

Yes the error says 2400m but it appears after rughply 40min = 60sec*40 = 2400 sec

### Steps/Code to Reproduce

- set the timeout to x, press enter
![image](https://github.com/cloud-py-api/app_api/assets/402891/24d900bf-1f07-449f-bb37-527a2c2305b3)
- Wait for the notification
![image](https://github.com/cloud-py-api/app_api/assets/402891/49bbb2b3-b176-406f-9cb7-44f00a20abff)
- Reload page
![image](https://github.com/cloud-py-api/app_api/assets/402891/d011c02f-49cf-4c15-a2a6-c058e43064ab)

### Expected Results

The timeout beeing saved, and respected in ExApp init.

### Actual Results

The timeout seem's to keep the default value, in the settings page
and
for also the ExApp init thows an error after the default value.

### Setup configuration

app_api = 2.5.1
nextcloud = 29

**Comment by tacruc** [comment]
Related to https://github.com/cloud-py-api/ai_image_generator_bot/issues/8

**Comment by andrey18106** [comment]
@tacruc Hi! Thank you for reporting this. It's an incorrect key in the UI. Will be fixed in the next AppAPI release.

For now, you can set this setting via CLI: `sudo -u www-data php occ config:app:set app_api init_timeout --value 3000 --type integer`

**Comment by tacruc** [comment]
Thanks for the fast spot.

**Comment by andrey18106** [comment]
@tacruc Please update this config setting with mixed type: `sudo -u www-data php occ config:app:set app_api init_timeout --value 3000 --type mixed`. I missed that we do not support the new appconfig interface with explicit types yet, it's only since NC29, from UI config won't be saved with another types than mixed because of type check.

**Comment by tacruc** [comment]
@andrey18106 thanks, that you thought giving the hint. Sofar I haven't observed any issues with the way I set it.
