### ISSUE TITLE
Unresponsive settings when demon is not available anymore

### ISSUE THREAD

**Issue by Rello** [cloud-py-api/app_api#307]
- I connected an external demon on an ionos testserver
- I forgot to delete the demon from the app api settings
- I can not enter the app api settings anymore
- `cURL error 7: Failed to connect to 93.90.204.71 port 2375 after 75002 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://93.90.204.71:2375/v1.41/_ping`

I had to remove the DB entry in ex_apps_daemons

**Comment by bigcat88** [comment]
Yes, you are right, if the DefaulDemon is not available, then applications even that are running on another deployment daemon - which is available - cannot be disabled from the UI, for example.
