### ISSUE TITLE
Allow unregistering app if it no longer running

### ISSUE THREAD

**Issue by marcelklehr** [cloud-py-api/app_api#316]
### Describe why it is important and where it will be useful

Sometimes the app has died or has been removed already by a sysadmin, but it's still registered in app_api. It is then not possible currently to unregister it, afaik.

### Describe your proposed solution

I would like to be able to unregister an app even if it's not running.

**Comment by bigcat88** [comment]
for CI you can use `--force` flag

**Comment by marcelklehr** [comment]
Ah, damn. Didn't see that- Thanks.
