### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by aef5748** [cloud-py-api/app_api#353]
Original translation:
"Check if the image is successfully pulled" : "撿茶室否成功拉取映像檔",

Correct translation:
"Check if the image is successfully pulled" : "檢查是否成功拉取映像檔",

Found in the following archives:
zh_TW.js
zh_TW.json
zh_HK.js
zh_HK.json

**Comment by andrey18106** [comment]
Hi @aef5748! Thank you for corrections.
Please, report this on [Transifex](https://app.transifex.com/nextcloud/nextcloud/app_api/), the translations are being updated automatically from there in this repository.

**Comment by aef5748** [comment]
Sorry, I don't have Transifex account.
