### ISSUE TITLE
Can test deployments work offline?

### ISSUE THREAD

**Issue by aef5748** [cloud-py-api/app_api#355]
I am already installed app_api and download relation image, like below:
test-deploy:release-cpu
test-deploy:release-cuda
context_chat_backend

Is it passable initial finished without network after create daemon?

Because when I disconnect external network, I got below message after create daemon and click test
```
file_get_contents(https://raw.githubusercontent.com/cloud-py-api/test-deploy/main/appinfo/info.xml): Failed to open stream: Connection timed out at /var/www/html/custom_apps/app_api/lib/Service/ExAppService.php#277
```

**Comment by bigcat88** [comment]
Hello. No, it is not supposed to work offline, we have no such feature at this moment.

**Comment by aef5748** [comment]
Thanks for your reply.

**Comment by bigcat88** [comment]
You're welcome
