### ISSUE TITLE
Does `unregisterExApp` removes bots registered by ExApp?

### ISSUE THREAD

**Issue by bigcat88** [cloud-py-api/app_api#58]
In case when Application itself for some reason/bug not removed it?

**Comment by bigcat88** [comment]
https://github.com/cloud-py-api/app_ecosystem_v2/blob/4b57d4f3a26106f2eb2444fb4020bfc8d2295801/lib/Service/AppEcosystemV2Service.php#L148-L168

Can't find it here, but maybe it is just hidden somewhere?

**Comment by andrey18106** [comment]
We do not store registered Talk bots in AppEcosystem, for proper management probably we should create as for other APIs add separate table for that? I'm just afraid to produce a lot of separate similar tables.
