### ISSUE TITLE
Failure to install on NC27.1.2

### ISSUE THREAD

**Issue by Aquilum** [cloud-py-api/app_api#94]
### Describe the bug

Installing from the store fails, with an apparently bad database query:

`An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'deploy_config' can't have a default value`

### Steps/Code to Reproduce

1. Install NextCloud 27.1.2
2. Attempt to install AppAPI

### Expected Results

AppAPI extension installs correctly

### Actual Results

Fails to install, citing query error.

### Setup configuration

NextCloud 27.1.2 with mySQL 8.0.34

**Comment by bigcat88** [comment]
Thanks for reporting this, we will try adding "mysql" to our test suite.

**Comment by bigcat88** [comment]
feel free to write to us to reopen issue if the problem still exists, thanks again for reporting problems to us.
