### ISSUE TITLE
recommend to use AIOs docker-socket-proxy container as if using normal docker?

### ISSUE THREAD

**Issue by szaimen** [cloud-py-api/app_api#98]
### Describe why it is important and where it will be useful

Currently the default deployment recommendation (making docker socket available for www-data user) is really insecure imho as the www-data user basically gets root privileges by doing so.

### Describe your proposed solution

Recommend to use docker-socket-proxy container by AIO which features at least a bit of protection and is made for this use case.

This would need some changes in the AIO container that I am willing to accept.

### Describe alternatives you've considered, if relevant

Recommending docker rootless instead?

**Comment by szaimen** [comment]
> Maybe I didn't get the question.
> 
> We did an integration with AIO to support automatic configuration. But the users (admins) can configure the daemons with their need, and for sure in this case they have to consider security on their own, they must be warned about rootless configuration.

What I meant was that maybe the deployment methods where you use rootful docker should be removed from the docs and instead deployment method via `docker-socket-proxy` in between should be added? 

So bascially my suggestion is to adjust the docs to always have a `docker-socket-proxy` in between Nextcloud and a `rootful` docker installation. 

So possible deployment methods are then:
- rootless docker on same or remote host
- ~~Docker in Docker~~ (Since this is not recommended by docker maybe it should be removed?)
- rootful docker on the same host but with a docker-socket-proxy in between
- rootful docker on a remote host also with a docker-socket-proxy in between
- AIO

**Comment by andrey18106** [comment]
@szaimen I made some adjustments in linked PR, please have a look at it if its fine for you now)

**Comment by szaimen** [comment]
Added some comments 👍

**Comment by szaimen** [comment]
What is mainly missing here now is this: https://github.com/cloud-py-api/app_api/pull/106#discussion_r1372896115

**Comment by bigcat88** [comment]
https://cloud-py-api.github.io/app_api/DeployConfigurations.html

<img width="863" alt="image" src="https://github.com/cloud-py-api/app_api/assets/13381981/cc317872-b666-44ab-ab5d-c3266612f482">

**Comment by szaimen** [comment]
Nice :)
